### ISSUE TITLE
Doesn't actually work / protect routes

### ISSUE THREAD

**Issue by simonmorley** [authy/authy-devise#21]
Problem One

Verify token page is nicely displayed after login. However, the routes are not actually protected and I am able to access all resources here in.

Problem Two

Sign-out route isn't excluded and I am unable to logout. I get redirected to the verify token screen. Why?

Am using the latest 1.5.1 gem from git directly.

Is there something missing from the documentation that I need to do or is this just broken as of the recent release?

**Comment by danpal** [comment]
@jonathansimmons this should already be fixed. Next release coming in a few weeks.

**Comment by danpal** [comment]
FIXED.
