### ISSUE TITLE
Devise-Authy assumes that every user model will be an authy enabled one

### ISSUE THREAD

**Issue by shaneog** [authy/authy-devise#28]
This is an incorrect assumption.

And the controller runs a check `with_authy_authentication? ` on models that do not have `:authy_authenticatable ` applied, causing my app to crash.

In my app I have two types of users (e.g. Admins, Users)
In this example _Admins_ would required `authy_authenticatable` but _Users_ don't. However, when a user tries to change a password - the call to `with_authy_authentication?` is made against the user model, causing a fatal error.

**Comment by RoseAndres** [comment]
Is there a standard way of doing this nowadays?

**Comment by philnash** [comment]
@RoseAndres The fix in 7597696 means that resources are only checked if they `respond_to?(:with_authy_authentication)` so this no longer errors.

What are you trying to do here if things aren't working for you?

**Comment by RoseAndres** [comment]
I implemented the `with_authy_authentication` method, but also have an overridden `after_sign_in_path`. When I sign in with a user that should use 2fa, but hasn't enabled authy yet, it's still taking me to the 2fa verify page, rather than the 2fa enable page.

**Comment by philnash** [comment]
How did you implement `with_authy_authentication`?

**Comment by philnash** [comment]
Are you trying to enforce 2FA on your users?

**Comment by RoseAndres** [comment]
We're trying to force 2FA on Users Associated with specific centers that require 2FA

In my User model:

```
def requires_twofa?
  is_twofa_teacher = self.has_role_slug('teacher') && self.fertility_care_center&.require_teacher_twofa
  is_twofa_client = self.has_role_slug('client') && self.fertility_care_center&.require_client_twofa
  is_customer_service = self.has_role_slug('customer_service')

  return is_twofa_teacher || is_twofa_client || is_customer_service
end

def with_authy_authentication?(request)
  requires_twofa?
end
```

**Comment by philnash** [comment]
The `with_authy_authentication` method is intended to gate sign in and redirect those that have Authy enabled to the verification page, that's why you're seeing the current behaviour.

The original implementation is:

```ruby
      def with_authy_authentication?(request)
        if self.authy_id.present? && self.authy_enabled
          return true
        end

        return false
      end
```

But you are trying to enforce the 2FA being enabled for your users. For this, you likely need to add your own controller action filter that checks if your user requires 2FA but doesn't have it enabled and then redirects to the enable page.

I would remove your implementation of `with_authy_authentication` and add something like this to the application controller.

```ruby
class ApplicationController < ActionController::Base
  before_action :require_2fa
 
  private
 
  def require_2fa
    return if params[:controller].start_with?("devise")
    # If there is a signed in user that does not have authy enabled and requires authy to be enabled.
    if user_signed_in? && !current_user.with_authy_authentication?(request) && current_user.requires_twofa?
      redirect_to user_enable_authy_path
    end
  end
end
```

**Comment by RoseAndres** [comment]
After doing some digging I arrived at the that conclusion and had started along a similar solution. 

Your solution above worked perfect. Thanks much!

**Comment by philnash** [comment]
Awesome, glad it helped!
