### ISSUE TITLE
Accepting incorrect Token while signing in

### ISSUE THREAD

**Issue by blackhawk21** [authy/authy-devise#32]
User while trying to sign-in is asked for Verification token, but at every alternate attempt after timeout of session incorrect token gets accepted and access is granted. Inspecting session object returns

{"user_id"=>10005, "user_password_checked"=>true, "user_remember_me"=>false, "warden.user.user.key"=>[[10005], "$2a$10$P7L6AIYNYQUA18Toya1ghe"], "warden.user.user.session"=>{:with_authy_authentication=>true, :id=>10005, "last_request_at"=>2014-12-03 12:30:15 UTC}, "session_id"=>"98530de7cdf50d3682dee7dff3382958", "last_user"=>"User", "_csrf_token"=>"Y8OQt1SxuYJRUgZbBJs3Oo72AtH0I3Q/qbVCYoxnzTM="}

**Comment by danpal** [comment]
looks like this was resolved. Closing. If you still have the same issue, please re-open.
