### ISSUE TITLE
Authy + Devise + ActiveAdmin

### ISSUE THREAD

**Issue by daniel-nelson** [authy/authy-devise#34]
I'm having trouble getting this to work with Devise and ActiveAdmin. The routes configuration we already have is:
```devise_for :admin_users, ActiveAdmin::Devise.config```

The routes configuration from the authy-devise readme is:
```
devise_for :users, :path_names => {
    :verify_authy => "/verify-token",
    :enable_authy => "/enable-two-factor",
    :verify_authy_installation => "/verify-installation"
}
```

Do you have an example of how to configure authy-devise to work with Devise + ActiveAdmin?

**Comment by daniel-nelson** [comment]
No. In the end, we switched from Devise to AuthLogic and are in the early phases of replacing ActiveAdmin with a custom admin solution.

**Comment by dcu** [comment]
@khelal @daniel-nelson We haven't tried active admin before, do you have an error message or something we can look at?

**Comment by danpal** [comment]
@daniel-nelson any update here. Do you have any error messages.

**Comment by daniel-nelson** [comment]
Hi @danpal, we switched from Devise to Authlogic and built our own admin (including Authy!) instead of ActiveAdmin.

**Comment by danpal** [comment]
Gotcha, I am going to close this in the meantime. IF you ever have this issue again let us know.

**Comment by eyefodder** [comment]
Going to add this here for people who do want to make this work.

`ActiveAdmin::Devise.config` just returns an object with routing defaults for using active admin and devise. All you really need to do is add in the devise authy controller. I found that if you are just using devise_authy out of the box it will work just fine. If you need to customize things (in my case, I wanted to use a different controller), you can just merge the values into the `ActiveAdmin::Devise.config` object:

```devise_for :admin_users, ActiveAdmin::Devise.config.deep_merge(controllers: {devise_authy: 'admin/two_factor_auth'})```

**Comment by muhammadumarkhan-vf** [comment]
@eyefodder Hope you doing well. 
Do you have the implementation of Authy + Devise + ActiveAdmin in any repo?
