### ISSUE TITLE
Link for phone call

### ISSUE THREAD

**Issue by shaneog** [authy/authy-devise#35]
I have phone calls enabled  for users, however I don't know how to provide that option in the UI for my users.
In `verify_authy_installation.html.erb` there is a link `authy_request_sms_link`. Is there a similar helper for phone calls?

**Comment by danpal** [comment]
We are starting to work on this. Thanks for letting us know.

**Comment by senekis** [comment]
@shaneog I already merged the pull request  #45 

Our next release should have this feature.
