### ISSUE TITLE
Entered API key is always returned as Invalid

### ISSUE THREAD

**Issue by blackhawk21** [authy/authy-devise#36]
Previously I use to validate entered API key using following method

  def validate_credentials
    errors.add(:api_key, I18n.t('authy.invalid_credentials')) if invalid_authy_credentials?
  end

  def invalid_authy_credentials?
    response = Authy::API.get_request('protected/json/verify/', :api_key => self.api_key)
    response.present? && response.has_key?('errors')
  end

It use to work with API key for my account, but while I tried the same yesterday, it's returning '{"message"=>"Invalid API key.", "success"=>false, "errors"=>{"message"=>"Invalid API key."}}'

I even tried with newly generated API key but the result is same.

In authy initialiser I have uri set as

Authy.api_uri = 'https://api.authy.com/'

**Comment by aslamj** [comment]
I'm facing the same issue.

**Comment by danpal** [comment]
We are starting to work on this. Thanks for letting us know.

**Comment by chrisnicola** [comment]
Starting? It's been 4 days.

**Comment by danpal** [comment]
Our sprints ran in 2 weeks intervals, so it's going to take a bit longer. We need to do QA etc - sorry it's taking so long.

**Comment by chrisnicola** [comment]
I'm confused, am I missing something about this? API keys are not working so people can't use the service at all and this is a low priority here?

**Comment by kakalos12** [comment]
I having this problem on my IPAD air 2 (IOS 9.1) too, Wil this fix be included in the app updates ?

**Comment by senekis** [comment]
@chrisnicola @aslamj @blackhawk21 are you still presenting this issue? I'm trying to reproduce it without success.

Please, can you give me more details to find the issue. Thanks.

**Comment by chrisnicola** [comment]
We've decided not to move forward with Authy for a few reasons, so I can't say if it is still occurring.

**Comment by bernardobarreto** [comment]
@senekis @danpal is this solved in 2020? I'm having the same issue apparently lol
