### ISSUE TITLE
authy-help doesn't do anything

### ISSUE THREAD

**Issue by matthewford** [authy/authy-devise#38]
<%= link_to '?', '#', :id => 'authy-help' %>

Seems to do nothing

**Comment by danpal** [comment]
We are starting to work on this. Thanks for letting us know.

**Comment by senekis** [comment]
If you want to set a message you need to configure the authy-form-helpers plugin like this: [Help tooltip documentation](https://github.com/authy/authy-form-helpers#help-tooltip), but you are right, it doesn't do anything in the gem right now and documentation is missing.

The next release should have documentation for that and the link will be commented in the view.

Thanks @matthewford :smile:
