### ISSUE TITLE
Is there a reason there isn't `after_authy_disabled_path_for` called after disable? 

### ISSUE THREAD

**Issue by sainejob** [authy/authy-devise#40]
Just curious why the `POST_disable_auth` method doesn't also call a method which can be easily overriden (ala `after_authy_enabled_path_for`)? 

Instead, it is hard-coded to `root_path`

**Comment by ZachBeta** [comment]
That seems really straightforward to PR. We may do this if we run into it as well, though I suspect you can fork and PR yourself if necessary.

**Comment by danpal** [comment]
We are starting to work on this. Thanks for letting us know.

**Comment by senekis** [comment]
@sainejob Thank you for your suggestion.

I made the change in the commit a58f117, so our next version is going to have this change. :smile:
