### ISSUE TITLE
Store something that indicates user is signed in with 2-factor

### ISSUE THREAD

**Issue by crazydog115** [authy/authy-devise#41]
I have an application that lets users sign in to devise with their username + password, or with Omniauth.

After installing `authy-devise`, the omniauth authentication method did not require users to enter their 2-factor token.

I was able to resolve that issue, but it got me thinking - why isn't there a way to query the user's current session to ensure that they are signed in with 2factor?

I think that in [DeviseAuthyController#POST_verify_authy](https://github.com/authy/authy-devise/blob/master/app/controllers/devise/devise_authy_controller.rb#L28), a session variable should be set that indicates that a user entered a valid token.

That would allow me to add a `before_filter` to the authenticated areas of my application to not only ensure that the user is signed in, but that they entered a valid 2-factor token. 

This would have caught my Omniauth issue, as the users' session would not have indicated that they entered a valid 2-factor token.

**Comment by danpal** [comment]
We are starting to work on this. Thanks for letting us know.
