### ISSUE TITLE
It's possible to bypass Authy during the installation session

### ISSUE THREAD

**Issue by barendt** [authy/authy-devise#43]
During a user's first session hitting my application they're prompted to enable Authy. After entering their cellphone number they're taken to the `verify-installation` route which asks the user to enter their Authy token. Instead of being required to enter a token, they can navigate elsewhere in the web application and continue on as an authenticated user. This appears to only be true of that session - a user who skips entering their token at that step and attempts to log in again later or from another browser is forced to enter a token before they can access the application.

**Comment by danpal** [comment]
We are starting to work on this. Thanks for letting us know.

**Comment by senekis** [comment]
See comments in the pull request #44
