### ISSUE TITLE
Generator's Use of `inject_into_file` Is Not Specific Enough

### ISSUE THREAD

**Issue by alexwilkinson** [authy/authy-devise#46]
We have noticed that if there are two blocks in the Devise initializer, after you run the generator, it will insert the commented out configuration example twice. Here is the result of that in our devise initializer:

```
Rails.application.config.to_prepare do
  # existing configuration here for devise layouts

  # ==> Devise Authy Authentication Extension
  # How long should the user's device be remembered for.
  # config.authy_remember_device = 1.month

end

Devise.setup do |config|
  # existing configuration here

  # ==> Devise Authy Authentication Extension
  # How long should the user's device be remembered for.
  # config.authy_remember_device = 1.month
end
```

The second block is where the code really should be. One idea we had on how to fix this would be to use the argument `:after` for `inject_into_file` to specify `Devise.setup do |config|` (or something similar). That way, it will always insert the code into the one correct block.

Here is some documentation that shows the use of the `after` argument:
http://www.rubydoc.info/github/wycats/thor/Thor/Actions:inject_into_file

The code in question for the generator is here:
https://github.com/authy/authy-devise/blob/master/lib/generators/devise_authy/install_generator.rb#L16

Thanks!

**Comment by danpal** [comment]
We are starting to work on this. Thanks for letting us know.

**Comment by senekis** [comment]
Thanks for reporting the issue. The next version will have the fix for that :smile:
