### ISSUE TITLE
Time based authentication

### ISSUE THREAD

**Issue by pardha-billa** [authy/authy-devise#57]
I have integrated authy-devise to my rails 3.2 application. Client asked me to enable two factor authentication once per day. Means two factor feature will be a one time per day deal.  Do we have such option.

**Comment by jacobnbrum** [comment]
Yeah, you can do something like that by changing the "remember device" cookie, from 1 month to one day. 
 This cookie is set in the file authy-devise/lib/devise-authy.rb
Something like `@@authy_remember_device = 1.day`

**Comment by miraj-p-11** [comment]
Is there any option to remember user based on their IP address. For eg: If my user(admin) is working from his office no need to verify using OTP. When he trying to access the same website from out off the office or different IP need to send OTP for verification.

**Comment by senekis** [comment]
Sorry the gem doesn't support the remember user based on their IP.

About the time based authentication @jacobnbrum is correct using `authy_remember_device` is the way to ask the two factor authentication once per day
