### ISSUE TITLE
remember_device not account specific

### ISSUE THREAD

**Issue by Gasparila** [authy/authy-devise#58]
Looking at https://github.com/authy/authy-devise/blob/f3fd125f1b8c9539a1a700d3198628cf4fe332cd/lib/devise-authy/controllers/helpers.rb#L12, the remember_device cookie has no link to the current account. This makes it trivial for any attacker to bypass two-factor authentication for a compromised account, rendering authy useless:
1. Attacker logs into their account with their username and password and two-factor authentication (this will give the attacker a valid remember_device cookie)
2. Attacker logs out
3. Attacker logs in to compromised account. Since the cookie is still set, require_token? will return false

**Comment by jacobnbrum** [comment]
I can confirm that this method works using the standard cookie.

**Comment by Gasparila** [comment]
Opened a PR to get this issue fixed as quickly as possible
