### ISSUE TITLE
Delayed tokens

### ISSUE THREAD

**Issue by pardha-billa** [authy/authy-devise#61]
Seems that functionality works fine. But my clients report that tokens take more than two minutes to reach out . I'm not sure whether this should be here or not but I should resolve the issue. So please let me know your thoughts.

**Comment by senekis** [comment]
@pardha-billa sorry for late response, the delayed tokens issue isn't related with the gem, it is related with our SMS/Call providers. Please contact us to support@authy.com to check your case and improve the delivery rate for your country.
