### ISSUE TITLE
Authy completely by passable

### ISSUE THREAD

**Issue by Gasparila** [authy/authy-devise#69]
At the end of the `check_request_and_redirect_to_verify_token` method (https://github.com/authy/authy-devise/blob/master/lib/devise-authy/controllers/helpers.rb#L53), the user is still signed in because the `warden.authenticate?` in Devise's `sign_in` (https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/sign_in_out.rb#L10) is not super clearly named and will re-authenticate the user (https://github.com/hassox/warden/blob/master/lib/warden/proxy.rb#L113)

As a result, the user is signed in at the end of this `before_filter` so a user can just change the url to a different endpoint and bypass 2fa entirely.

A quick fix is to add `sign_out` to `check_request_and_redirect_to_verify_token` (https://github.com/authy/authy-devise/blob/master/lib/devise-authy/controllers/helpers.rb#L53) which has some extra callbacks and will stop the user from being reauthenticated

**Comment by senekis** [comment]
Related to #70
