### ISSUE TITLE
Verification code via email not via otp or call

### ISSUE THREAD

**Issue by yogeshmanjhi1993** [authy/authy-devise#79]
I have integrated the authy-devise and it works well. But now i am facing a problem, in verify_authy.html.erb 
there are two links for sms and phone verification 
  <%= authy_request_sms_link %>
  <%= authy_request_phone_call_link %>

But i want that user should be able to request the verification code via email also i tried searching a lot in issues and googled it a lot but could not find anything any idea how can i achieve it 
Any help is greatly appreciated thanks

**Comment by senekis** [comment]
Sorry, we don't support to send the otp via email.

**Comment by senekis** [comment]
I will add this as a feature request in our backlog to be considered in the future.

Thanks @yogeshmanjhi1993

**Comment by yogeshmanjhi1993** [comment]
@senekis Thanks will look forward to it in future :+1:
