### ISSUE TITLE
Can you guys wrap a CDN around the S3 installers download links

### ISSUE THREAD

**Issue by rocketspacer** [authy/authy-devise#88]
If cost is a problem, I recommend using [Cloudflare](https://cloudflare.com/) it's a very popular free CDN. I live in Asia, and the 59.5MB installer requires me to download for at least 2 hours.

I know this might not be the appropriate channel to discuss this, but I think this is the fastest way to reach you guys. I'm sorry for any inconveniences that this may cause you.

**Comment by philnash** [comment]
Hey @rocketspacer, not sure what you're talking about here. Is this a problem with authy-devise specifically?

**Comment by rocketspacer** [comment]
No, it's not related to authy-devise. I post it here because I can't find any appropriate channel to discuss this problem.

Your direct download link is really slow (https://authy.com/download)
Because it hit directly to S3, I'm just suggesting using CDN to wrap around them.

**Comment by philnash** [comment]
Oh, ok, for the desktop app?

I'll pass this feedback onto the team, but I'll close this issue as it's not about authy-devise. Thanks!
